project_name: knoxctl

builds:
  - binary: knoxctl
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/accuknox/accuknox-cli-v2/pkg/version.GitSummary={{.Version}} -X github.com/accuknox/accuknox-cli-v2/pkg/version.BuildDate={{.Date}}
    flags:
      - -trimpath
    hooks:
      pre:
        - make prebuild GOOS={{ .Os }} GOARCH={{ .Arch }}
      post:
        - rm -rf pkg/vm/rra

signs:
  - cmd: cosign
    certificate: '${artifact}.cert'
    args:
      - sign-blob
      - '--output-certificate=${certificate}'
      - '--output-signature=${signature}'
      - '${artifact}'
      - --yes
    artifacts: all
    output: true
