// SPDX-License-Identifier: Apache-2.0
// Copyright 2022 Authors of KubeArmor

package cmd

import (
	"fmt"
	"os"
	"strings"

	"github.com/accuknox/accuknox-cli-v2/pkg/recommend"
	"github.com/spf13/cobra"
)

var recommendOptions recommend.Options

// recommendCmd represents the recommend command
var recommendCmd = &cobra.Command{
	Use:   "recommend",
	Short: "Recommend Policies",
	Long:  `Recommend hardening policies generated by Discovery Engine`,
	RunE: func(cmd *cobra.Command, args []string) error {
		rawArgs := strings.Join(os.Args[2:], " ")
		parseArgs, err := recommend.ProcessArgs(rawArgs)
		if err != nil {
			return fmt.Errorf("error processing args: %v", err)
		}

		if err := recommend.Recommend(client, parseArgs); err != nil {
			return err
		}
		return nil
	},
}

func init() {
	rootCmd.AddCommand(recommendCmd)

	recommendCmd.Flags().StringSliceVarP(&recommendOptions.Labels, "labels", "l", []string{}, "User defined labels for policy (comma separated)")
	recommendCmd.Flags().StringSliceVarP(&recommendOptions.Policy, "policy", "p", []string{"KubeArmorPolicy"}, "Types of policy that can be recommended: KubeArmorPolicy|KyvernoPolicy")
	recommendCmd.Flags().StringSliceVarP(&recommendOptions.Namespace, "namespace", "n", []string{}, "Filter by Namespace")
	recommendCmd.Flags().StringVarP(&recommendOptions.Outdir, "outdir", "o", "out", "Output folder to write policies")
	recommendCmd.Flags().StringSliceVarP(&recommendOptions.Tags, "tag", "t", []string{}, "Tags to apply. Eg. PCI-DSS,MITRE")
	recommendCmd.Flags().StringVarP(&recommendOptions.Grpc, "gRPC", "", "", "gRPC address of discovery engine")
}
